language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
deploy:
  on:
    branch: master
  provider: npm
  email: "${NPM_EMAIL_ADDRESS}"
  api_key: "${NPM_API_TOKEN}"
notifications:
  email: false
before_install:
  - npm install -g grunt-cli
after_success:
  - npm run coveralls
  - npm run codeclimate
